// Biblioteca de ações do Plano de Ação Vivo NR-1 (gerada a partir de docs/biblioteca-plano-de-acao-nr1.md)
export type ControlLevel = 1 | 2 | 3

export type LibraryAction = {
  key: string        // único dentro do fator: 'a1','a2','a3'...
  level: ControlLevel
  title: string      // título da ação (ex: "Política antiassédio formal e canal de denúncia sigiloso")
  how: string        // o "Como" (resumido, 1 frase)
  who: string        // responsável sugerido, SEM o "(editável)" (ex: "RH + Direção + CIPA")
  startWeek: number  // semana de início (use 1 quando não houver; ações de origem começam em 1)
  dueWeek: number    // semana de prazo; use 0 para ações "contínuas"
  howMuch?: string   // o "Quanto", se houver
  evidence: string   // a evidência principal da ação
}

export type LibraryFactor = {
  topicNum: number   // 1 a 13
  name: string       // nome do fator (ex: "Assédio de Qualquer Natureza")
  whatIs: string     // texto do "O que é"
  whyTreat: string   // texto do "Por que tratar"
  indicators: string[] // lista dos indicadores (quebre o texto de Indicadores em itens)
  actions: LibraryAction[]
}

export const ACTION_LIBRARY: LibraryFactor[] = [
  {
    topicNum: 1,
    name: "Assédio de Qualquer Natureza",
    whatIs:
      "ocorrência de assédio moral, assédio sexual ou condutas desrespeitosas/humilhantes no ambiente de trabalho, somada à ausência de um canal seguro e sigiloso para denúncia.",
    whyTreat:
      "assédio é um dos fatores psicossociais mais graves da NR-1 — gera adoecimento (CID F43 reação a estresse, F32 depressão, F41 ansiedade), afastamentos, passivo trabalhista e responsabilização civil/criminal da empresa. Exige medida com responsável e prazo, além de tratamento sigiloso de cada caso.",
    indicators: [
      "Nº de denúncias recebidas/apuradas no prazo",
      "tempo médio de apuração",
      "reincidência",
      "afastamentos por CID F43/F32/F41",
      "nota do fator na reavaliação",
    ],
    actions: [
      {
        key: "a1",
        level: 1,
        title: "Política antiassédio formal e canal de denúncia sigiloso",
        how: "Redigir política com condutas vedadas e sanções; abrir canal sigiloso (e-mail/0800/formulário externo); garantir anonimato e não retaliação; divulgar a todos",
        who: "RH + Direção + CIPA",
        startWeek: 1,
        dueWeek: 4,
        howMuch: "Baixo (ferramenta de canal + tempo de RH/jurídico)",
        evidence: "Política antiassédio assinada, registros do canal (sigilosos), procedimentos de apuração, listas de presença de treinamentos, materiais de campanha.",
      },
      {
        key: "a2",
        level: 1,
        title: "Fluxo de apuração com prazo e proteção ao denunciante",
        how: "Definir fluxo de apuração com prazo e proteção ao denunciante",
        who: "comitê de ética/RH",
        startWeek: 1,
        dueWeek: 6,
        evidence: "procedimento de apuração documentado, com prazos e garantia de não retaliação.",
      },
      {
        key: "a3",
        level: 2,
        title: "Treinamento obrigatório de liderança sobre assédio e respeito",
        how: "Realizar treinamento obrigatório de liderança sobre assédio e respeito",
        who: "RH",
        startWeek: 1,
        dueWeek: 10,
        evidence: "lista de presença + conteúdo aplicado.",
      },
      {
        key: "a4",
        level: 2,
        title: "Campanha de conscientização para todos os colaboradores",
        how: "Realizar campanha de conscientização para todos os colaboradores",
        who: "RH/Comunicação",
        startWeek: 1,
        dueWeek: 12,
        evidence: "materiais divulgados + registro de adesão.",
      },
      {
        key: "a5",
        level: 3,
        title: "Acolhimento e apoio psicológico à vítima",
        how: "Oferecer acolhimento e apoio psicológico à vítima",
        who: "RH/SESMT",
        startWeek: 1,
        dueWeek: 0,
        evidence: "registro de encaminhamento e suporte (sigiloso).",
      },
    ],
  },
  {
    topicNum: 2,
    name: "Suporte e Apoio no Ambiente de Trabalho",
    whatIs:
      "percepção de falta de apoio da liderança, dos colegas e do RH, e ausência de espaço para expressar dificuldades sem medo de julgamento ou punição.",
    whyTreat:
      "baixo suporte social é fator de risco psicossocial reconhecido pela ISO 45003 e amplifica estresse, ansiedade (CID F41) e quadros depressivos (CID F32). Suporte adequado é fator de proteção que reduz afastamentos e turnover — exige medida com responsável e prazo.",
    indicators: [
      "Frequência de 1:1 realizados",
      "nº de atendimentos no canal de RH",
      "clima/eNPS",
      "absenteísmo",
      "afastamentos por CID F32/F41",
      "nota do fator na reavaliação",
    ],
    actions: [
      {
        key: "a1",
        level: 1,
        title: "Rotina estruturada de apoio da liderança (1:1 e escuta ativa)",
        how: "Agenda fixa de 1:1; roteiro de escuta (dificuldades, recursos, bem-estar); registrar pendências e dar retorno",
        who: "Gestores de área + RH",
        startWeek: 1,
        dueWeek: 6,
        howMuch: "Sem custo direto (tempo de gestão)",
        evidence: "Atas/registros de 1:1, divulgação do canal de RH, listas de presença, programa de rede de apoio, registros do PAE.",
      },
      {
        key: "a2",
        level: 1,
        title: "Canal direto e acessível com o RH",
        how: "Disponibilizar canal direto e acessível com o RH",
        who: "RH",
        startWeek: 1,
        dueWeek: 5,
        evidence: "canal divulgado (horário/forma de contato) + registro de atendimentos.",
      },
      {
        key: "a3",
        level: 2,
        title: "Capacitação de líderes em liderança de apoio e escuta ativa",
        how: "Capacitar líderes em liderança de apoio e escuta ativa",
        who: "RH",
        startWeek: 1,
        dueWeek: 10,
        evidence: "lista de presença + plano aplicado.",
      },
      {
        key: "a4",
        level: 2,
        title: "Rede de apoio entre pares (padrinho/madrinha ou grupos de apoio)",
        how: "Implantar rede de apoio entre pares (padrinho/madrinha ou grupos de apoio)",
        who: "RH/lideranças",
        startWeek: 1,
        dueWeek: 12,
        evidence: "programa documentado + participantes.",
      },
      {
        key: "a5",
        level: 3,
        title: "Canal de apoio psicológico/PAE (Programa de Apoio ao Empregado)",
        how: "Disponibilizar canal de apoio psicológico/PAE (Programa de Apoio ao Empregado)",
        who: "RH/SESMT",
        startWeek: 1,
        dueWeek: 0,
        evidence: "registro do canal e encaminhamentos.",
      },
    ],
  },
  {
    topicNum: 3,
    name: "Má Gestão de Mudanças Organizacionais",
    whatIs:
      "condução de mudanças (reestruturações, novos processos, troca de liderança, cortes) sem comunicação clara, transparência ou cuidado com a sensação de segurança no emprego.",
    whyTreat:
      "mudanças mal comunicadas geram insegurança, boatos, ansiedade (CID F41) e reação ao estresse (CID F43), reduzindo engajamento e elevando o turnover. A gestão de mudanças é fator psicossocial da ISO 45003 — exige medida com responsável e prazo.",
    indicators: [
      "Percepção de clareza sobre mudanças (pesquisa)",
      "nº de dúvidas respondidas",
      "turnover no período de mudança",
      "afastamentos por CID F41/F43",
      "nota do fator na reavaliação",
    ],
    actions: [
      {
        key: "a1",
        level: 1,
        title: "Plano de comunicação de mudanças transparente",
        how: "Definir o que/quando/como comunicar; comunicar antes dos boatos; explicar motivos e impactos; abrir espaço para dúvidas e dar retorno",
        who: "Direção + RH + gestores",
        startWeek: 1,
        dueWeek: 6,
        howMuch: "Sem custo direto (tempo de gestão/RH)",
        evidence: "Plano de comunicação, comunicados enviados, atas de reuniões participativas, FAQ publicado, registros de acolhimento.",
      },
      {
        key: "a2",
        level: 1,
        title: "Envolvimento da equipe nas decisões de mudança",
        how: "Promover envolvimento da equipe nas decisões de mudança",
        who: "gestores + RH",
        startWeek: 1,
        dueWeek: 8,
        evidence: "registros de reuniões participativas e ajustes incorporados a partir do feedback.",
      },
      {
        key: "a3",
        level: 2,
        title: "Capacitação de líderes em gestão de mudanças",
        how: "Capacitar líderes em gestão de mudanças",
        who: "RH",
        startWeek: 1,
        dueWeek: 10,
        evidence: "lista de presença + conteúdo aplicado.",
      },
      {
        key: "a4",
        level: 2,
        title: "Canal de dúvidas e FAQ sobre as mudanças",
        how: "Criar canal de dúvidas e FAQ sobre as mudanças",
        who: "RH/Comunicação",
        startWeek: 1,
        dueWeek: 9,
        evidence: "FAQ publicado + registro de dúvidas respondidas.",
      },
      {
        key: "a5",
        level: 3,
        title: "Apoio aos colaboradores impactados (acolhimento/recolocação)",
        how: "Oferecer apoio aos colaboradores impactados (acolhimento/recolocação)",
        who: "RH/SESMT",
        startWeek: 1,
        dueWeek: 0,
        evidence: "registro de acolhimento e suporte oferecido.",
      },
    ],
  },
  {
    topicNum: 4,
    name: "Baixa Clareza de Papel ou Função",
    whatIs:
      "falta de instruções claras sobre responsabilidades, metas e expectativas, deixando o colaborador sem saber exatamente o que se espera dele.",
    whyTreat:
      "a ambiguidade de papel é fator psicossocial clássico (ISO 45003) que gera estresse crônico, ansiedade (CID F41) e esgotamento (CID Z73), além de retrabalho, conflitos e queda de desempenho. Exige medida com responsável e prazo.",
    indicators: [
      "% de cargos com descrição atualizada",
      "% de colaboradores com metas claras",
      "retrabalho/erros",
      "afastamentos por CID F41/Z73",
      "nota do fator na reavaliação",
    ],
    actions: [
      {
        key: "a1",
        level: 1,
        title: "Descrição de cargo e definição clara de responsabilidades",
        how: "Descrever atribuições, entregas esperadas e limites de decisão; validar com o colaborador; disponibilizar documento acessível",
        who: "Gestor da área + RH",
        startWeek: 1,
        dueWeek: 6,
        howMuch: "Sem custo direto (tempo de gestão/RH)",
        evidence: "Descrições de cargo, planilha de metas validadas, listas de presença, registros de feedback e alinhamento.",
      },
      {
        key: "a2",
        level: 1,
        title: "Definição e alinhamento de metas e expectativas (SMART)",
        how: "Definir e alinhar metas e expectativas (SMART)",
        who: "gestores",
        startWeek: 1,
        dueWeek: 8,
        evidence: "metas registradas e validadas com cada colaborador.",
      },
      {
        key: "a3",
        level: 2,
        title: "Treinamento de gestores em delegação e comunicação de expectativas",
        how: "Treinar gestores em delegação e comunicação de expectativas",
        who: "RH",
        startWeek: 1,
        dueWeek: 10,
        evidence: "lista de presença + conteúdo aplicado.",
      },
      {
        key: "a4",
        level: 2,
        title: "Rotina de feedback e alinhamento periódico",
        how: "Implantar rotina de feedback e alinhamento periódico",
        who: "gestores",
        startWeek: 1,
        dueWeek: 12,
        evidence: "registros de feedback/alinhamento.",
      },
      {
        key: "a5",
        level: 3,
        title: "Apoio ao colaborador sobrecarregado pela ambiguidade",
        how: "Oferecer apoio ao colaborador sobrecarregado pela ambiguidade",
        who: "RH/SESMT",
        startWeek: 1,
        dueWeek: 0,
        evidence: "registro de orientação/apoio oferecido.",
      },
    ],
  },
  {
    topicNum: 5,
    name: "Baixas Recompensas e Reconhecimento",
    whatIs:
      "ausência de reconhecimento do esforço pela liderança, falta de feedback construtivo regular e baixa valorização das entregas e das pessoas.",
    whyTreat:
      "desequilíbrio esforço-recompensa é gatilho reconhecido de adoecimento mental (CID F32 depressão, F48 outros transtornos neuróticos, Z73 burnout), desengajamento, queda de produtividade e turnover. Fator de risco ocupacional pela NR-1 — exige medida com responsável e prazo.",
    indicators: [
      "Índice de reconhecimento em pesquisa de clima",
      "engajamento (eNPS)",
      "rotatividade voluntária",
      "nº de feedbacks 1:1 realizados",
      "nota do fator na reavaliação",
    ],
    actions: [
      {
        key: "a1",
        level: 1,
        title: "Estruturar ritual de reconhecimento e cultura de feedback",
        how: "Implantar ritual mensal de reconhecimento (individual e de equipe); definir critérios claros do que se reconhece; treinar líderes para dar feedback específico e construtivo (não só corretivo); registrar reconhecimentos",
        who: "Liderança da área + RH",
        startWeek: 1,
        dueWeek: 6,
        howMuch: "Sem custo direto (tempo de gestão); opcional verba simbólica de premiação",
        evidence: "Atas de ritual de reconhecimento, registros de 1:1, política de mérito revisada, listas de presença de treinamento, prints do canal de reconhecimento.",
      },
      {
        key: "a2",
        level: 1,
        title: "Revisar política de valorização e progressão",
        how: "Revisar política de valorização e progressão",
        who: "RH + diretoria",
        startWeek: 1,
        dueWeek: 10,
        evidence: "documento de critérios de mérito/progressão revisado e comunicado.",
      },
      {
        key: "a3",
        level: 1,
        title: "Definir feedback estruturado nas reuniões 1:1",
        how: "Definir feedback estruturado nas reuniões 1:1",
        who: "liderança",
        startWeek: 1,
        dueWeek: 8,
        evidence: "modelo de 1:1 e registro das primeiras rodadas.",
      },
      {
        key: "a4",
        level: 2,
        title: "Treinar líderes em reconhecimento e feedback",
        how: "Treinar líderes em reconhecimento e feedback",
        who: "RH",
        startWeek: 1,
        dueWeek: 12,
        evidence: "lista de presença.",
      },
      {
        key: "a5",
        level: 2,
        title: "Implantar canal de reconhecimento entre pares",
        how: "Implantar canal de reconhecimento entre pares",
        who: "RH",
        startWeek: 1,
        dueWeek: 14,
        evidence: "print/registro do canal ativo.",
      },
      {
        key: "a6",
        level: 3,
        title: "Canal de escuta e apoio psicológico",
        how: "Disponibilizar canal de escuta e apoio psicológico",
        who: "RH/SESMT",
        startWeek: 1,
        dueWeek: 0,
        evidence: "registro do canal.",
      },
    ],
  },
  {
    topicNum: 6,
    name: "Baixo Controle no Trabalho / Falta de Autonomia",
    whatIs:
      "pouca liberdade para decidir como executar as próprias tarefas, baixa confiança da empresa nas pessoas e excesso de controle e supervisão (microgestão).",
    whyTreat:
      "baixo controle combinado a alta demanda é o clássico modelo demanda-controle de Karasek para risco psicossocial — eleva estresse crônico, adoecimento (CID F43 reações ao estresse, F32 depressão, Z73 burnout) e absenteísmo. Fator de risco ocupacional pela NR-1 — exige medida com responsável e prazo.",
    indicators: [
      "Percepção de autonomia em pesquisa de clima",
      "nº de aprovações/etapas removidas",
      "absenteísmo",
      "rotatividade",
      "nota do fator na reavaliação",
    ],
    actions: [
      {
        key: "a1",
        level: 1,
        title: "Redesenhar autonomia e reduzir microgestão",
        how: "Mapear onde há aprovações/controles redundantes; definir o que a equipe pode decidir sozinha; estabelecer alçadas claras; substituir microgestão por acompanhamento por resultado; alinhar combinados com a equipe",
        who: "Gestor da área + RH",
        startWeek: 1,
        dueWeek: 6,
        howMuch: "Sem custo direto (tempo de gestão)",
        evidence: "Matriz de alçadas (RACI), atas de revisão de processos, listas de presença de treinamentos, registros de check-in, registro do canal de apoio.",
      },
      {
        key: "a2",
        level: 1,
        title: "Definir matriz de decisão e alçadas",
        how: "Definir matriz de decisão e alçadas",
        who: "liderança + RH",
        startWeek: 1,
        dueWeek: 8,
        evidence: "matriz de responsabilidades/alçadas (ex.: RACI) publicada.",
      },
      {
        key: "a3",
        level: 1,
        title: "Revisar metas e processos para foco em resultado, não em controle de passos",
        how: "Revisar metas e processos para foco em resultado, não em controle de passos",
        who: "gestor da área",
        startWeek: 1,
        dueWeek: 10,
        evidence: "ata de revisão de processos.",
      },
      {
        key: "a4",
        level: 2,
        title: "Capacitar líderes em delegação e gestão por confiança",
        how: "Capacitar líderes em delegação e gestão por confiança",
        who: "RH",
        startWeek: 1,
        dueWeek: 12,
        evidence: "lista de presença.",
      },
      {
        key: "a5",
        level: 2,
        title: "Treinar equipe em autonomia e tomada de decisão",
        how: "Treinar equipe em autonomia e tomada de decisão",
        who: "RH",
        startWeek: 1,
        dueWeek: 14,
        evidence: "lista de presença.",
      },
      {
        key: "a6",
        level: 3,
        title: "Canal de apoio psicológico e escuta sobre clima",
        how: "Disponibilizar canal de apoio psicológico e escuta sobre clima",
        who: "RH/SESMT",
        startWeek: 1,
        dueWeek: 0,
        evidence: "registro do canal.",
      },
    ],
  },
  {
    topicNum: 7,
    name: "Baixa Justiça Organizacional",
    whatIs:
      "percepção de critérios injustos ou pouco transparentes de avaliação, desigualdade de tratamento entre áreas e pessoas, e falta de transparência em decisões sensíveis como promoções e desligamentos.",
    whyTreat:
      "injustiça organizacional percebida está fortemente associada a adoecimento mental (CID F32 depressão, F43 reações ao estresse, Z73 burnout), queda de confiança, conflitos e turnover. Fator de risco ocupacional pela NR-1 — exige medida com responsável e prazo.",
    indicators: [
      "Percepção de justiça/transparência em pesquisa de clima",
      "nº de contestações abertas e resolvidas",
      "conflitos reportados",
      "rotatividade",
      "nota do fator na reavaliação",
    ],
    actions: [
      {
        key: "a1",
        level: 1,
        title: "Padronizar critérios justos e transparentes de avaliação e decisão",
        how: "Documentar critérios de avaliação/promoção/desligamento; aplicar de forma igual entre áreas; comunicar regras a todos; criar rito de explicação de decisões sensíveis; registrar justificativas",
        who: "RH + diretoria",
        startWeek: 1,
        dueWeek: 8,
        howMuch: "Sem custo direto (tempo de RH/gestão)",
        evidence: "Documento de critérios de avaliação/promoção/desligamento, fluxo de contestação, protocolo de desligamento, registros de comunicação, listas de presença, registro da ouvidoria.",
      },
      {
        key: "a2",
        level: 1,
        title: "Implantar canal de revisão/contestação de decisões",
        how: "Implantar canal de revisão/contestação de decisões",
        who: "RH",
        startWeek: 1,
        dueWeek: 10,
        evidence: "fluxo de contestação documentado e divulgado.",
      },
      {
        key: "a3",
        level: 1,
        title: "Padronizar processo de desligamento humanizado e transparente",
        how: "Padronizar processo de desligamento humanizado e transparente",
        who: "RH + liderança",
        startWeek: 1,
        dueWeek: 12,
        evidence: "protocolo de desligamento documentado.",
      },
      {
        key: "a4",
        level: 2,
        title: "Treinar líderes em decisões justas e comunicação transparente",
        how: "Treinar líderes em decisões justas e comunicação transparente",
        who: "RH",
        startWeek: 1,
        dueWeek: 14,
        evidence: "lista de presença.",
      },
      {
        key: "a5",
        level: 2,
        title: "Comunicar amplamente as regras e critérios à equipe",
        how: "Comunicar amplamente as regras e critérios à equipe",
        who: "RH/comunicação interna",
        startWeek: 1,
        dueWeek: 12,
        evidence: "registro da comunicação (e-mail/mural/reunião).",
      },
      {
        key: "a6",
        level: 3,
        title: "Canal de ouvidoria/escuta e apoio psicológico",
        how: "Disponibilizar canal de ouvidoria/escuta e apoio psicológico",
        who: "RH/SESMT",
        startWeek: 1,
        dueWeek: 0,
        evidence: "registro do canal.",
      },
    ],
  },
  {
    topicNum: 8,
    name: "Eventos Violentos ou Traumáticos",
    whatIs:
      "exposição a violência, ameaças, assédio grave, assaltos, acidentes graves ou episódios de forte impacto emocional no ambiente de trabalho.",
    whyTreat:
      "exposição a eventos traumáticos pode gerar transtorno de estresse pós-traumático (CID F43.1 TEPT), reações agudas ao estresse (F43.0), depressão (F32) e afastamentos prolongados. É um dos riscos psicossociais mais graves — pode demandar resposta imediata. Fator de risco ocupacional pela NR-1 — exige medida com responsável e prazo.",
    indicators: [
      "Nº de incidentes registrados",
      "tempo de resposta pós-incidente",
      "nº de atendimentos psicológicos",
      "afastamentos por F43/F32",
      "nota do fator na reavaliação",
    ],
    actions: [
      {
        key: "a1",
        level: 1,
        title: "Implantar protocolo de prevenção e resposta a eventos violentos/traumáticos",
        how: "Mapear situações de risco de violência; definir medidas preventivas (controle de acesso, protocolos de atendimento, segurança); criar fluxo pós-incidente (acolhimento imediato, comunicação, acionamento de apoio psicológico, registro/CAT quando aplicável); fazer análise de causa para evitar repetição",
        who: "SESMT + RH + liderança",
        startWeek: 1,
        dueWeek: 6,
        howMuch: "Custo variável (segurança/apoio psicológico) — definir com diretoria",
        evidence: "Protocolo pós-incidente, plano de medidas preventivas, registros de incidentes e CAT, atas de análise de causa, listas de presença, registros de apoio psicológico.",
      },
      {
        key: "a2",
        level: 1,
        title: "Definir medidas preventivas de segurança e ameaça",
        how: "Definir medidas preventivas de segurança e ameaça",
        who: "SESMT + segurança",
        startWeek: 1,
        dueWeek: 8,
        evidence: "plano de medidas preventivas implantado.",
      },
      {
        key: "a3",
        level: 1,
        title: "Criar fluxo de comunicação e registro de incidentes (incluindo CAT)",
        how: "Criar fluxo de comunicação e registro de incidentes (incluindo CAT)",
        who: "SESMT + RH",
        startWeek: 1,
        dueWeek: 8,
        evidence: "formulário/registro de incidentes e fluxo de CAT.",
      },
      {
        key: "a4",
        level: 2,
        title: "Treinar equipe em prevenção e conduta diante de eventos violentos",
        how: "Treinar equipe em prevenção e conduta diante de eventos violentos",
        who: "SESMT/RH",
        startWeek: 1,
        dueWeek: 12,
        evidence: "lista de presença.",
      },
      {
        key: "a5",
        level: 2,
        title: "Capacitar líderes em primeiros cuidados psicológicos (acolhimento pós-incidente)",
        how: "Capacitar líderes em primeiros cuidados psicológicos (acolhimento pós-incidente)",
        who: "RH",
        startWeek: 1,
        dueWeek: 12,
        evidence: "lista de presença.",
      },
      {
        key: "a6",
        level: 3,
        title: "Apoio psicológico imediato e acompanhamento pós-incidente",
        how: "Oferecer apoio psicológico imediato e acompanhamento pós-incidente (acionável em até 24–48h após evento)",
        who: "RH/SESMT + psicólogo/EAP",
        startWeek: 1,
        dueWeek: 0,
        evidence: "registro de atendimentos e acompanhamento de casos.",
      },
    ],
  },
  {
    topicNum: 9,
    name: "Baixa Demanda no Trabalho / Subcarga",
    whatIs:
      "falta de atividades, desafios ou estímulo no trabalho — tempo ocioso, subutilização das habilidades da pessoa e tarefas repetitivas que geram desânimo, tédio e perda de propósito.",
    whyTreat:
      "a subcarga é tão adoecedora quanto o excesso. Gera desengajamento, queda de autoestima, tédio crônico (boreout), sintomas depressivos (CID F32) e ansiosos (CID F41), além de turnover de talentos que se sentem desperdiçados. Fator de risco ocupacional pela NR-1 — exige medida com responsável e prazo.",
    indicators: [
      "Índice de engajamento",
      "tempo ocioso reportado",
      "adesão a treinamentos/projetos",
      "rotatividade de talentos",
      "nota do fator na reavaliação",
    ],
    actions: [
      {
        key: "a1",
        level: 1,
        title: "Enriquecimento e redesenho das funções (job enrichment)",
        how: "Mapear competências ociosas x atividades atuais; incluir tarefas mais complexas, projetos próprios e poder de decisão; alinhar com cada colaborador o novo escopo",
        who: "Gestor da área + RH",
        startWeek: 1,
        dueWeek: 8,
        howMuch: "Sem custo direto (tempo de gestão)",
        evidence: "Matriz de rodízio, PDIs, listas de presença, registros de mentoria, prints do canal de apoio.",
      },
      {
        key: "a2",
        level: 1,
        title: "Rotação de funções e participação em projetos",
        how: "Promover rotação de funções e participação em projetos",
        who: "gestor da área",
        startWeek: 1,
        dueWeek: 10,
        evidence: "matriz de rodízio e lista de participantes.",
      },
      {
        key: "a3",
        level: 1,
        title: "Atribuição de novos desafios e metas de desenvolvimento",
        how: "Atribuir novos desafios e metas de desenvolvimento",
        who: "liderança",
        startWeek: 1,
        dueWeek: 12,
        evidence: "plano individual de desenvolvimento (PDI).",
      },
      {
        key: "a4",
        level: 2,
        title: "Trilha de capacitação e requalificação",
        how: "Oferecer trilha de capacitação e requalificação",
        who: "RH",
        startWeek: 1,
        dueWeek: 12,
        evidence: "lista de presença e certificados.",
      },
      {
        key: "a5",
        level: 2,
        title: "Programa de mentoria e troca de conhecimento",
        how: "Implantar programa de mentoria e troca de conhecimento",
        who: "RH + lideranças",
        startWeek: 1,
        dueWeek: 14,
        evidence: "registro de encontros de mentoria.",
      },
      {
        key: "a6",
        level: 3,
        title: "Escuta ativa e canal de apoio para desmotivação",
        how: "Oferecer escuta ativa e canal de apoio para desmotivação",
        who: "RH",
        startWeek: 1,
        dueWeek: 0,
        evidence: "registro das conversas e do canal de apoio.",
      },
    ],
  },
  {
    topicNum: 10,
    name: "Sobrecarga de Trabalho / Excesso de Demandas",
    whatIs: "volume e pressão de tarefas acima do que a equipe consegue realizar no horário normal.",
    whyTreat:
      "principal gatilho de burnout, afastamentos (CID Z73/F43), absenteísmo e turnover. Fator de risco ocupacional pela NR-1 — exige medida com responsável e prazo.",
    indicators: [
      "Horas extras",
      "absenteísmo",
      "afastamentos por saúde mental",
      "rotatividade do setor",
      "nota do fator na reavaliação",
    ],
    actions: [
      {
        key: "a1",
        level: 1,
        title: "Diagnóstico e redistribuição de carga",
        how: "Levantar tarefas x tempo real; remanejar/eliminar o que não agrega; alinhar com a equipe",
        who: "Gestor da área + RH",
        startWeek: 1,
        dueWeek: 6,
        howMuch: "Sem custo direto (tempo de gestão)",
        evidence: "Atas de reunião, nova tabela de metas, comprovante de contratação, listas de presença, prints do canal de apoio.",
      },
      {
        key: "a2",
        level: 1,
        title: "Revisão de metas inatingíveis",
        how: "Revisar metas inatingíveis",
        who: "liderança/diretoria",
        startWeek: 1,
        dueWeek: 8,
        evidence: "ata de revisão das metas.",
      },
      {
        key: "a3",
        level: 1,
        title: "Dimensionamento da equipe",
        how: "Dimensionar a equipe conforme a demanda",
        who: "gestor + RH",
        startWeek: 1,
        dueWeek: 12,
        evidence: "parecer de dimensionamento / plano de reforço.",
      },
      {
        key: "a4",
        level: 2,
        title: "Treinamento de gestão do tempo e prioridades",
        how: "Treinar a equipe em gestão do tempo e prioridades",
        who: "RH",
        startWeek: 1,
        dueWeek: 10,
        evidence: "lista de presença.",
      },
      {
        key: "a5",
        level: 2,
        title: "Capacitar liderança a reconhecer sinais de exaustão",
        how: "Capacitar liderança a reconhecer sinais de exaustão",
        who: "RH",
        startWeek: 1,
        dueWeek: 14,
        evidence: "lista de presença.",
      },
      {
        key: "a6",
        level: 3,
        title: "Canal de apoio psicológico",
        how: "Disponibilizar canal de apoio psicológico",
        who: "RH/SESMT",
        startWeek: 1,
        dueWeek: 0,
        evidence: "registro do canal.",
      },
    ],
  },
  {
    topicNum: 11,
    name: "Maus Relacionamentos no Local de Trabalho",
    whatIs:
      "conflitos frequentes, rivalidade excessiva, clima negativo e desentendimentos mal resolvidos entre colegas ou entre equipe e liderança.",
    whyTreat:
      "relações tóxicas corroem a saúde mental, elevam estresse, ansiedade (CID F41) e quadros depressivos (CID F32), e são porta de entrada para assédio moral. Resultam em absenteísmo, queda de produtividade e turnover. Fator de risco ocupacional pela NR-1 — exige medida com responsável e prazo.",
    indicators: [
      "Nota de clima organizacional",
      "número de conflitos/denúncias registrados e resolvidos",
      "absenteísmo",
      "rotatividade",
      "nota do fator na reavaliação",
    ],
    actions: [
      {
        key: "a1",
        level: 1,
        title: "Diagnóstico de clima e mediação de conflitos",
        how: "Aplicar escuta individual e em grupo; mapear os pontos de atrito; conduzir mediação estruturada com acordos de convivência registrados",
        who: "RH + gestor da área",
        startWeek: 1,
        dueWeek: 6,
        howMuch: "Sem custo direto (tempo de RH/gestão) ou custo de mediador externo, se necessário",
        evidence: "Atas de mediação, acordo de convivência assinado, ata de revisão de metas, listas de presença, registros do canal.",
      },
      {
        key: "a2",
        level: 1,
        title: "Acordo de convivência e regras de respeito da equipe",
        how: "Estabelecer acordo de convivência e regras de respeito da equipe",
        who: "gestor da área + equipe",
        startWeek: 1,
        dueWeek: 8,
        evidence: "acordo assinado pela equipe.",
      },
      {
        key: "a3",
        level: 1,
        title: "Revisão de metas e estruturas que estimulam rivalidade nociva",
        how: "Revisar metas e estruturas que estimulam rivalidade nociva",
        who: "liderança + RH",
        startWeek: 1,
        dueWeek: 10,
        evidence: "ata de revisão das metas.",
      },
      {
        key: "a4",
        level: 2,
        title: "Treinamento em comunicação não violenta e resolução de conflitos",
        how: "Treinar a equipe em comunicação não violenta e resolução de conflitos",
        who: "RH",
        startWeek: 1,
        dueWeek: 12,
        evidence: "lista de presença.",
      },
      {
        key: "a5",
        level: 2,
        title: "Capacitação de líderes em mediação e clima",
        how: "Capacitar líderes em mediação e clima",
        who: "RH",
        startWeek: 1,
        dueWeek: 14,
        evidence: "certificado/lista de presença.",
      },
      {
        key: "a6",
        level: 3,
        title: "Canal de denúncia e apoio psicológico",
        how: "Disponibilizar canal de denúncia e apoio psicológico",
        who: "RH",
        startWeek: 1,
        dueWeek: 0,
        evidence: "registro do canal e dos atendimentos.",
      },
    ],
  },
  {
    topicNum: 12,
    name: "Trabalho em Condições de Difícil Comunicação",
    whatIs:
      "barreiras para se comunicar e receber informações no momento certo, causadas por turnos diferentes, distância física entre equipes ou trabalho externo/em campo.",
    whyTreat:
      "a falha de comunicação gera retrabalho, erros, sensação de exclusão e insegurança, alimentando estresse e ansiedade (CID F41). A pessoa que não recebe a informação certa na hora certa se sente desamparada e desconectada. Fator de risco ocupacional pela NR-1 — exige medida com responsável e prazo.",
    indicators: [
      "Número de falhas/erros por ruído de comunicação",
      "retrabalho",
      "nota de \"recebo as informações que preciso\" na pesquisa",
      "absenteísmo",
      "nota do fator na reavaliação",
    ],
    actions: [
      {
        key: "a1",
        level: 1,
        title: "Mapeamento de falhas e padronização dos canais de comunicação",
        how: "Levantar pontos de ruído; definir canal único por tipo de mensagem (urgente x informativo); criar rotina de repasse entre turnos e equipes externas",
        who: "Gestor da área + RH",
        startWeek: 1,
        dueWeek: 8,
        howMuch: "Sem custo direto ou custo de ferramenta de comunicação (app/mural), se necessário",
        evidence: "Mapa de canais, modelos de passagem de turno, prints do mural central, registros de entrega de ferramentas, listas de presença.",
      },
      {
        key: "a2",
        level: 1,
        title: "Rotina de passagem de turno e handoff estruturado",
        how: "Implantar rotina de passagem de turno e handoff estruturado",
        who: "gestor da área",
        startWeek: 1,
        dueWeek: 10,
        evidence: "modelo de passagem de turno preenchido.",
      },
      {
        key: "a3",
        level: 1,
        title: "Ponto único de informação acessível a todos",
        how: "Criar ponto único de informação acessível a todos",
        who: "gestor + RH",
        startWeek: 1,
        dueWeek: 12,
        evidence: "print/registro do canal central ativo.",
      },
      {
        key: "a4",
        level: 2,
        title: "Fornecimento de ferramentas adequadas de comunicação",
        how: "Fornecer ferramentas adequadas de comunicação",
        who: "gestão + TI",
        startWeek: 1,
        dueWeek: 12,
        evidence: "registro de entrega/configuração das ferramentas.",
      },
      {
        key: "a5",
        level: 2,
        title: "Treinamento em comunicação clara e objetiva",
        how: "Treinar a equipe em comunicação clara e objetiva",
        who: "RH",
        startWeek: 1,
        dueWeek: 14,
        evidence: "lista de presença.",
      },
      {
        key: "a6",
        level: 3,
        title: "Canal de escuta para ruídos e canal de apoio",
        how: "Disponibilizar canal de escuta para ruídos e canal de apoio",
        who: "RH",
        startWeek: 1,
        dueWeek: 0,
        evidence: "registro do canal.",
      },
    ],
  },
  {
    topicNum: 13,
    name: "Trabalho Remoto e Isolado",
    whatIs:
      "sensação de afastamento e solidão de quem trabalha remoto ou isolado — pouco contato presencial, falta de acompanhamento da liderança e sentimento de não pertencer à equipe.",
    whyTreat:
      "o isolamento prolongado alimenta solidão, sintomas depressivos (CID F32), ansiedade (CID F41) e exaustão (CID Z73), além de desengajamento e perda de vínculo com a empresa. Sem acompanhamento, problemas e sobrecarga passam despercebidos. Fator de risco ocupacional pela NR-1 — exige medida com responsável e prazo.",
    indicators: [
      "Frequência de check-ins realizados",
      "nota de pertencimento/conexão na pesquisa",
      "absenteísmo",
      "afastamentos por saúde mental",
      "rotatividade de remotos",
      "nota do fator na reavaliação",
    ],
    actions: [
      {
        key: "a1",
        level: 1,
        title: "Rituais de conexão da equipe e check-ins regulares",
        how: "Instituir check-in 1:1 periódico do gestor, reunião curta de equipe (daily/semanal) e rituais de integração; combinar canais e horários de disponibilidade",
        who: "Gestor da área + RH",
        startWeek: 1,
        dueWeek: 6,
        howMuch: "Sem custo direto (tempo de gestão)",
        evidence: "Agenda e registros dos 1:1, registros dos encontros presenciais, listas de presença, registro de duplas (buddy), prints do canal de apoio.",
      },
      {
        key: "a2",
        level: 1,
        title: "Acompanhamento ativo da liderança (1:1 estruturado)",
        how: "Realizar acompanhamento ativo da liderança (1:1 estruturado)",
        who: "liderança",
        startWeek: 1,
        dueWeek: 8,
        evidence: "registro/agenda dos 1:1.",
      },
      {
        key: "a3",
        level: 1,
        title: "Encontros presenciais ou híbridos periódicos",
        how: "Promover encontros presenciais ou híbridos periódicos",
        who: "gestor + RH",
        startWeek: 1,
        dueWeek: 12,
        evidence: "registro/foto dos encontros e lista de presença.",
      },
      {
        key: "a4",
        level: 2,
        title: "Capacitação de líderes em gestão de equipes remotas",
        how: "Capacitar líderes em gestão de equipes remotas",
        who: "RH",
        startWeek: 1,
        dueWeek: 12,
        evidence: "lista de presença.",
      },
      {
        key: "a5",
        level: 2,
        title: "Programa de integração e \"buddy\" para isolados",
        how: "Implantar programa de integração e \"buddy\" para isolados",
        who: "RH",
        startWeek: 1,
        dueWeek: 14,
        evidence: "registro de duplas e ações de integração.",
      },
      {
        key: "a6",
        level: 3,
        title: "Canal de apoio psicológico e escuta para solidão",
        how: "Disponibilizar canal de apoio psicológico e escuta para solidão",
        who: "RH",
        startWeek: 1,
        dueWeek: 0,
        evidence: "registro do canal e dos atendimentos.",
      },
    ],
  },
]
